<?php
declare(strict_types=1);
$pageTitle = 'DartSystem – Professionelles Darttraining';
$pageDescription = 'Professionelles Darttraining mit strukturierten Leveln, Ranglisten und persönlichem Fortschritt.';
require __DIR__ . '/includes/header.php';
?>
<main>
    <section class="hero">
        <div class="hero-image" aria-hidden="true"></div><div class="hero-shade" aria-hidden="true"></div>
        <div class="hero-content"><p class="eyebrow"><span></span>Training neu gedacht</p><h1>Triff nicht nur das Board.<br><em>Triff dein Potenzial.</em></h1><p class="hero-copy">DartSystem verbindet präzises Spielgefühl, strukturierte Herausforderungen und persönliche Bestwerte. Trainiere mit einem klaren Ziel und sieh, wie du mit jedem Wurf besser wirst.</p><div class="hero-actions"><a class="button" href="/download.php" target="_blank" rel="noopener">DartSystem herunterladen <span>↗</span></a><a class="text-link" href="/produkt.php"><span class="play">▶</span> Funktionen entdecken</a></div><div class="hero-proof"><div class="avatars"><span>01</span><span>50</span><span>∞</span></div><div><strong>Training · Fortschritt · Wettbewerb</strong><small>Alles in deinem DartSystem</small></div></div></div>
        <div class="live-card"><div class="live-top"><span><i></i> ONLINE-PROFIL</span><b>LEVEL 12</b></div><div class="live-score"><span>Bestwert</span><strong>167</strong><small>Highscore synchronisiert</small></div><div class="live-row"><span>Genauigkeit <b>63,4%</b></span><span>Fortschritt <b>72%</b></span></div><div class="live-track"><span style="width:72%"></span></div><p>Nächste Aufgabe <strong>Level 13 →</strong></p></div>
    </section>
    <section class="intro-strip"><p>Ein System für dein gesamtes Spiel.</p><div><span>01</span><strong>Gezieltes Training</strong></div><div><span>02</span><strong>Messbarer Fortschritt</strong></div><div><span>03</span><strong>Faire Ranglisten</strong></div></section>
    <section class="section split-section"><div class="section-copy"><p class="kicker">Alles in deinem Profil</p><h2>Dein Fortschritt bleibt bei dir.</h2><p>Level, Erfahrung, Präzision und Highscores werden in deinem persönlichen Profil übersichtlich zusammengeführt. So erkennst du sofort, was bereits sitzt und woran du als Nächstes arbeiten kannst.</p><a class="arrow-link" href="/register.php">Spielerkonto erstellen <span>→</span></a></div><div class="analysis-board"><div class="analysis-head"><span>SPIELERFORTSCHRITT</span><b>Aktueller Stand</b></div><div class="big-stat"><strong>63,4</strong><span>Trefferquote<br><i>+8,2%</i></span></div><div class="chart"><i style="height:34%"></i><i style="height:46%"></i><i style="height:39%"></i><i style="height:58%"></i><i style="height:53%"></i><i style="height:71%"></i><i style="height:66%"></i><i style="height:86%"></i></div><div class="analysis-stats"><span>Level <b>12</b></span><span>Erfahrung <b>4.850</b></span><span>Highscores <b>18</b></span></div></div></section>
    <section class="section photo-section"><div class="feature-photo" role="img" aria-label="Dartspieler im konzentrierten Training"></div><div class="photo-copy"><p class="kicker">Für echte Spieler</p><h2>Vom ersten Wurf bis zur Bestform.</h2><p>DartSystem macht Training motivierend, ohne die Leistung aus den Augen zu verlieren. Jede Aufgabe hat ein klares Ziel und jeder Bestwert einen sichtbaren Platz.</p><ul class="check-list"><li>Direktes und glaubwürdiges Spielgefühl</li><li>Über 100 Level und Herausforderungen</li><li>Bestwerte für jede Aufgabe</li><li>Persönliches Spielerprofil</li></ul><a class="button" href="/training.php">Training ansehen <span>→</span></a></div></section>
    <section class="section platform-section"><div class="download-visual" role="img" aria-label="Darts im Bullseye"></div><div><p class="kicker">Direkt loslegen</p><h2>DartSystem herunterladen.</h2><p>Hol dir die aktuelle Version, melde dich mit deinem Spielerkonto an und starte dein nächstes Training.</p><div class="platform-row"><span>Schnelle Installation</span><span>Persönliches Profil</span><span>Regelmäßige Aktualisierungen</span></div><a class="button" href="/download.php" target="_blank" rel="noopener">Zum Download <span>↗</span></a></div></section>
    <section class="final-cta"><p class="eyebrow"><span></span>Bereit für den nächsten Wurf?</p><h2>Dein bestes Spiel<br>beginnt <em>jetzt.</em></h2><a class="button" href="/register.php">Kostenlos registrieren <span>→</span></a><small>Ein Konto für Programm, Fortschritt und Ranglisten.</small></section>
</main>
<?php require __DIR__ . '/includes/footer.php'; ?>
