<?php
declare(strict_types=1);
$pageTitle = 'DartSystem – Professionelles Darttraining';
$pageDescription = 'Das professionelle Unity-Dartprogramm mit realistischem Spielgefühl, Level-System, Online-Ranglisten und persönlichem Fortschritt.';
require __DIR__ . '/includes/header.php';
?>
<main>
    <section class="hero">
        <div class="hero-image" aria-hidden="true"></div><div class="hero-shade" aria-hidden="true"></div>
        <div class="hero-content"><p class="eyebrow"><span></span>Professionelles Dart-Programm</p><h1>Triff nicht nur das Board.<br><em>Triff dein Potenzial.</em></h1><p class="hero-copy">DartSystem verbindet realistische Unity-Physik, strukturierte Level und Online-Ranglisten. Installiere das Programm, trainiere gezielt und verfolge deinen Fortschritt auf jedem Wurf.</p><div class="hero-actions"><a class="button" href="<?= e(mega_download_url()) ?>" target="_blank" rel="noopener">Programm herunterladen <span>↗</span></a><a class="text-link" href="/produkt.php"><span class="play">▶</span> Funktionen entdecken</a></div><div class="hero-proof"><div class="avatars"><span>01</span><span>50</span><span>∞</span></div><div><strong>Unity · Render · TiDB</strong><small>Ein verbundenes DartSystem</small></div></div></div>
        <div class="live-card"><div class="live-top"><span><i></i> ONLINE-PROFIL</span><b>LEVEL 12</b></div><div class="live-score"><span>Bestwert</span><strong>167</strong><small>Highscore synchronisiert</small></div><div class="live-row"><span>Genauigkeit <b>63,4%</b></span><span>Fortschritt <b>72%</b></span></div><div class="live-track"><span style="width:72%"></span></div><p>Nächste Aufgabe <strong>Level 13 →</strong></p></div>
    </section>
    <section class="intro-strip"><p>Ein System für dein gesamtes Spiel.</p><div><span>01</span><strong>Unity-Programm</strong></div><div><span>02</span><strong>Cloud-Fortschritt</strong></div><div><span>03</span><strong>Online-Ranglisten</strong></div></section>
    <section class="section split-section"><div class="section-copy"><p class="kicker">Programm & Profil verbunden</p><h2>Dein Fortschritt endet nicht beim Schließen des Spiels.</h2><p>Login, Level, Erfahrung, Präzision und Highscores laufen über dieselbe sichere Render-API und deine TiDB-Cloud-Datenbank. Auf der Website siehst du den Stand deines Spielerprofils.</p><a class="arrow-link" href="/register.php">Spielerkonto erstellen <span>→</span></a></div><div class="analysis-board"><div class="analysis-head"><span>SPIELERFORTSCHRITT</span><b>Live aus TiDB Cloud</b></div><div class="big-stat"><strong>63,4</strong><span>Trefferquote<br><i>+8,2%</i></span></div><div class="chart"><i style="height:34%"></i><i style="height:46%"></i><i style="height:39%"></i><i style="height:58%"></i><i style="height:53%"></i><i style="height:71%"></i><i style="height:66%"></i><i style="height:86%"></i></div><div class="analysis-stats"><span>Level <b>12</b></span><span>Experience <b>4.850</b></span><span>Highscores <b>18</b></span></div></div></section>
    <section class="section photo-section"><div class="feature-photo" role="img" aria-label="Dartspieler im Training"></div><div class="photo-copy"><p class="kicker">Entwickelt für echte Spieler</p><h2>Vom Wohnzimmer bis ans Oche.</h2><p>DartSystem macht Training spielerisch, ohne die Leistung aus den Augen zu verlieren. Jede Aufgabe hat ein klares Ziel und jeder Bestwert einen Platz.</p><ul class="check-list"><li>Realistische Dart-Physik in Unity</li><li>Über 100 Level und Herausforderungen</li><li>Weltweite Highscores pro Level</li><li>Persönliches Spielerprofil</li></ul><a class="button" href="/training.php">Training ansehen <span>→</span></a></div></section>
    <section class="section platform-section"><p class="kicker">Aktueller Build</p><h2>DartSystem herunterladen.</h2><p>Alle verfügbaren Builds liegen im offiziellen MEGA-Ordner. Neue Versionen können dort ohne Änderung der Website bereitgestellt werden.</p><div class="platform-row"><span>Windows 10/11</span><span>Weitere Unity-Builds</span><span>Sicherer MEGA-Download</span></div><a class="button" href="<?= e(mega_download_url()) ?>" target="_blank" rel="noopener">Zum Download <span>↗</span></a></section>
    <section class="final-cta"><p class="eyebrow"><span></span>Bereit für den nächsten Wurf?</p><h2>Dein bestes Spiel<br>beginnt <em>jetzt.</em></h2><a class="button" href="/register.php">Kostenlos registrieren <span>→</span></a><small>Ein Konto für Programm, Fortschritt und Ranglisten.</small></section>
</main>
<?php require __DIR__ . '/includes/footer.php'; ?>
