<?php
declare(strict_types=1);
require __DIR__ . '/_bootstrap.php';
api_require_method('POST');
if (!is_admin()) api_error('Administrator-Anmeldung erforderlich.', 401);
$input = api_input(false);
$csrf = $_SERVER['HTTP_X_CSRF_TOKEN'] ?? ($input['csrf_token'] ?? null);
if (!csrf_is_valid(is_string($csrf) ? $csrf : null)) api_error('Ungültiges CSRF-Token.', 403);
$customerName = trim((string)($input['customer_name'] ?? ''));
$customerEmail = trim((string)($input['customer_email'] ?? ''));
$deviceId = trim((string)($input['device_id'] ?? ''));
$licenseType = strtolower(trim((string)($input['license_type'] ?? 'full')));
$maxActivations = filter_var($input['max_activations'] ?? 1, FILTER_VALIDATE_INT);
$expiresIn = filter_var($input['expires_in'] ?? 365, FILTER_VALIDATE_INT);
if ($customerName === '') api_error('Kundenname ist erforderlich.');
if ($customerEmail !== '' && !filter_var($customerEmail, FILTER_VALIDATE_EMAIL)) api_error('Ungültige E-Mail-Adresse.');
if (!in_array($licenseType, ['full','trial','subscription','club'], true)) api_error('Ungültiger Lizenztyp.');
if ($maxActivations === false || $maxActivations < 1 || $maxActivations > 999) api_error('Maximale Aktivierungen müssen zwischen 1 und 999 liegen.');
if ($expiresIn === false || $expiresIn < 0 || $expiresIn > 3650) api_error('Ungültige Gültigkeitsdauer.');
$part = static fn(): string => strtoupper(bin2hex(random_bytes(2)));
$licenseKey = implode('-', [$part(), $part(), $part(), $part()]);
$expiresAt = $expiresIn > 0 ? date('Y-m-d H:i:s', strtotime('+' . $expiresIn . ' days')) : null;
$pdo = getDBConnection();
$stmt = $pdo->prepare('INSERT INTO licenses (license_key, key_hash, customer_name, customer_email, device_id, license_type, max_activations, expires_at, is_active) VALUES (:key, :hash, :name, :email, :device, :type, :max, :expires, 1)');
$stmt->execute(['key' => $licenseKey, 'hash' => hash('sha256', $licenseKey), 'name' => $customerName, 'email' => $customerEmail ?: null, 'device' => $deviceId ?: null, 'type' => $licenseType, 'max' => $maxActivations, 'expires' => $expiresAt]);
api_response(['success' => true, 'license_key' => $licenseKey, 'id' => $pdo->lastInsertId(), 'expires_at' => $expiresAt], 201);
